### ISSUE TITLE
Why I get 0.61 on lr=1e-1 and epoch=100?

### ISSUE THREAD

**Issue by RosabanksiaeAit** [ChawDoe/LeNet5-MNIST-PyTorch#1]

**Comment by ChawDoe** [comment]
The initial weight of network is crucial to the final perfomance.  
You can run multiple models to see which is best. I think the best performance would be bigger than 0.61. 
What's more, 100 epoch may be too much for this task. The model may be over-fitting the training data.

**Comment by maruncong** [comment]
self.fc2 = nn.Linear(120, 64) #84
        self.relu4 = nn.ReLU()
        self.fc3 = nn.Linear(64, 10) #84
model里面两个84改成64

**Comment by ChawDoe** [comment]
> ```
>     self.fc2 = nn.Linear(120, 64) #84
>     self.relu4 = nn.ReLU()
>     self.fc3 = nn.Linear(64, 10) #84
> ```
> 
> model里面两个84改成64

Maybe it's a good idea to avoid over-fitting.
![image](https://user-images.githubusercontent.com/25716030/139409463-d3dba7ea-1ffb-4efe-997d-f544d2bcc5d8.png)
