### ISSUE TITLE
_error variable in train.py

### ISSUE THREAD

**Issue by lopes-leonardo** [ChawDoe/LeNet5-MNIST-PyTorch#3]
There're two "_error" mentions on line 28 of train.py. One of them is the variable, resulting in a variable not defined error:

![image](https://user-images.githubusercontent.com/56077977/116727208-9f816280-a9ba-11eb-9e7f-19374cd92333.png)

**Comment by ChawDoe** [comment]
Yes. I found that I made an error and I fixed it now.

**Comment by ChawDoe** [comment]
Thanks for your check!
