### ISSUE TITLE
Basic model structure issue

### ISSUE THREAD

**Issue by ranlychan** [ChawDoe/LeNet5-MNIST-PyTorch#9]
It is believed that LeNet-5 uses Sigmoid as activation function and uses AvgPooling. ReLU and MaxPooling were adopted in AlexNet instead of LeNet-5, which can be confirmed on Wikipedia: [https://en.wikipedia.org/wiki/LeNet](https://en.wikipedia.org/wiki/LeNet).

**Comment by ChawDoe** [comment]
Thank you @ranlychan! You found the difference! As the implemented architecture in this repo has shown its high accuracy and it has been used by many researchers, I will mention this in the readme instead of modifying it again.
